#!/usr/bin/python
# -*- coding: utf-8 -*-
import re
f=open('hindi_corpus.txt','r')
for line in f:
	line=line.replace('\"',' ')
	line=line.replace('.',' ')
	line=line.replace('`',' ')
	line=line.replace('>',' ')
	line=line.replace('<',' ')
	line=line.replace('~',' ')
	line=line.replace(',',' ')
	line=line.replace('\'',' ')
	line=line.replace(')',' ')
	line=line.replace('[',' ')
	line=line.replace(']',' ')
	line=line.replace('\\',' ')
	line=line.replace('/',' ')
	line=line.replace('…',' ')
	line=line.replace('(',' ')
	line=line.replace(':',' ')
	line=line.replace(';',' ')
	line=line.replace('%',' ')
	line=line.replace('’',' ')
	line=line.replace('‘',' ')
	line=line.replace('!',' ')
	line=line.replace('“',' ')
	line=line.replace('”',' ')
	line=line.replace('*',' ')
	line=line.replace('?',' ')
	line=line.replace('।',' ')
	line=line.replace('-',' ')
	line=line.replace('\t',' ')
	line=line.replace('१',' ')
	line=line.replace('२',' ')
	line=line.replace('३',' ')
	line=line.replace('४',' ')
	line=line.replace('५',' ')
	line=line.replace('६',' ')
	line=line.replace('७',' ')
	line=line.replace('८',' ')
	line=line.replace('९',' ')
	line=line.replace('०',' ')
	line = re.sub(r'[a-zA-Z0-9]', ' ', line) 
	print line.strip()
